name: Terraform-Apply-Destroy

on:
  workflow_dispatch:
    inputs:
      condition:
        description: If you want to apply (Yes) or if you want to destroy (No)
        required: true
      	

env:
  aws-region: ap-south-1
  aws_s3_bucket: karan098
  tfstate_file: terrastate.tfstate
  db_table: karan01

jobs:
  terraformInit:
    name: terraInit
    runs-on: ubuntu-latest
    
  steps:
    - name: checkout
      uses: actions/checkout@v3

    - name: Terraform HasiCorp SetUp
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.2.6

    - name: AWS Credentials Configuration
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ env.aws-region }}
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      
    - name: terraform format
      run:
        terraform fmt
      
    - name: terraform init
      run:
        terraform init -reconfigure -backend-config="bucket=$aws_s3_bucket" -backend-config="key=$tfstate_file" -backend-config="dynamodb_table=$db_table"

    - name: terraform validate
      run:
        terraform validate

    - name: terraform plan
      run:
        terraform plan

    - name: terraform apply
      if: ${{ github.event.inputs.condition == 'Yes' }}
      run:
        terraform apply -auto-approve

    - name: terraform destroy
      if: ${{ github.event.inputs.condition == 'No' }}
      run:
        terraform destroy -auto-approve
